# Generated by Django 5.0.7 on 2024-07-12 22:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_category_post_notification_comments_bookmark"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comments",
            new_name="Comment",
        ),
    ]
