# Generated by Django 5.0.7 on 2024-07-21 22:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_rename_comments_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="title",
            new_name="comment",
        ),
    ]
