# Generated by Django 5.0.7 on 2024-07-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_rename_title_comment_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
